#!/usr/bin/env python3
"""Compare the matlab_ref layer against the Octave goldens (ADC-350).

Pure NumPy, no build: loads the CSVs under matlab_ref/goldens/ (generated by
golden_linearized_gen.m / golden_init_gen.m / golden_dt_gen.m from
RieMOM2D_Electrostatic_periodic) and asserts that hyqmom15/matlab_ref reproduces
them. This is the external-oracle validation deferred from ADC-349; the source
and one-step goldens (native solver) are validated in the wave-case PRs.

Run: ``python3 hyqmom15/matlab_ref/check_goldens.py`` (0 = OK, 1 = mismatch).
"""
from __future__ import annotations

import dataclasses
import pathlib
import sys

import numpy as np

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from matlab_ref import (  # noqa: E402
    diocotron_max_speed,
    eigenmode,
    get_case,
    init_constant_field,
    init_diocotron_field,
    init_electrostatic_wave_field,
    init_fluid_wave_field,
    init_magnetic_wave_field,
    linearized_jacobian_electrostatic,
    linearized_jacobian_fluid,
    linearized_jacobian_magnetostatic,
    compute_dt,
)

G = pathlib.Path(__file__).resolve().parent / "goldens"
GOLDEN_NP = 16  # golden_init_gen.m resolution
DT_CASES = ["fluid_wave", "electrostatic_wave", "magnetic_wave", "dicotron", "constant"]


def _load(name):
    return np.atleast_2d(np.loadtxt(G / name, delimiter=","))


def _cplx(a):
    return a[:, 0] + 1j * a[:, 1]


def _match_eigs(w, eg):
    """Worst-pair distance of an order-free 1-to-1 nearest-neighbour matching.

    ``w`` and ``eg`` hold the same eigenvalue multiset in unspecified order.
    Each computed eigenvalue is paired with a distinct golden one (closest
    pairs fixed first) and the largest pairing distance is returned, so a
    cosmetic reordering scores ~0 while a genuine eigenvalue shift scores its
    true gap. This replaces ``np.sort_complex``, whose lexicographic
    (real, then imag) tie-break is FP-fragile for near-degenerate or
    imaginary-axis modes (see ``check_linearized``).
    """
    w = np.asarray(w)
    eg = np.asarray(eg)
    assert w.shape == eg.shape and w.ndim == 1, "eigenvalue vectors must match"
    dist = np.abs(w[:, None] - eg[None, :])
    used_w = np.zeros(w.size, dtype=bool)
    used_g = np.zeros(eg.size, dtype=bool)
    worst = 0.0
    for _ in range(w.size):
        masked = np.where(used_w[:, None] | used_g[None, :], np.inf, dist)
        i, j = np.unravel_index(np.argmin(masked), masked.shape)
        worst = max(worst, float(masked[i, j]))
        used_w[i] = used_g[j] = True
    return worst


def check_linearized():
    jac = {
        "fluid_wave": linearized_jacobian_fluid(4 * np.pi, 0.0),
        "electrostatic_wave": linearized_jacobian_electrostatic(0.0, 4 * np.pi, 1 / 30),
        "magnetic_wave": linearized_jacobian_magnetostatic(2 * np.pi, 4 * np.pi, 1 / 20, -40),
    }
    for name, J in jac.items():
        raw = _load("lin_%s_jac.csv" % name)
        Jg = raw[:, :15] + 1j * raw[:, 15:]
        np.testing.assert_allclose(J, Jg, rtol=0, atol=1e-12, err_msg="%s Jacobian" % name)
        w = np.linalg.eigvals(J)
        eg = _cplx(_load("lin_%s_eigvals.csv" % name))
        # Order-free comparison: np.sort_complex sorts lexicographically (real,
        # then imag), which is unstable for the two magnetic_wave modes on the
        # imaginary axis (real parts ~3e-15 apart, imag parts -0.026 and +0.491).
        # FP noise in the near-zero real part can swap their order between w and
        # eg, so an elementwise compare fails on a ~0.5 cosmetic permutation even
        # though the eigenvalue *sets* still agree to ~4e-13.
        dmax = _match_eigs(w, eg)
        assert dmax <= 1e-9, (
            "%s eigenvalues: nearest-neighbour match exceeds tol "
            "(max pairing distance %.3e > 1e-9)" % (name, dmax))
        _, vec = eigenmode(J, 15)
        vg = _cplx(_load("lin_%s_eigvec.csv" % name))
        np.testing.assert_allclose(vec, vg, rtol=0, atol=1e-9, err_msg="%s phase-pinned eigenvector" % name)
    ms = _load("maxspeed.csv")
    es_i = init_electrostatic_wave_field(get_case("electrostatic_wave"), dmax_policy="intended").max_speed
    es_a = init_electrostatic_wave_field(get_case("electrostatic_wave"), dmax_policy="as_written").max_speed
    assert abs(es_i - (ms[0, 0] + 1j * ms[0, 1])) < 1e-9, "es intended max_speed"
    assert abs(es_a - (ms[1, 0] + 1j * ms[1, 1])) < 1e-9, "es as_written max_speed"
    assert abs(diocotron_max_speed(get_case("dicotron")) - ms[2, 0]) < 1e-9, "diocotron max_speed"
    return "linearized OK (3 Jacobians bit, eigenvalues, phase-pinned eigenvectors, 3 max_speed)"


def _golden_field(tag):
    raw = _load("init_%s.csv" % tag)
    return np.stack([raw[k * GOLDEN_NP:(k + 1) * GOLDEN_NP, :] for k in range(15)], axis=0)


def check_init():
    def at_golden_np(name):
        return dataclasses.replace(get_case(name), Np=GOLDEN_NP)

    fields = [
        ("fluid_wave", init_fluid_wave_field(at_golden_np("fluid_wave")).M),
        ("electrostatic_wave", init_electrostatic_wave_field(at_golden_np("electrostatic_wave")).M),
        ("magnetic_wave", init_magnetic_wave_field(at_golden_np("magnetic_wave")).M),
        ("magnetic_wave_aswritten", init_magnetic_wave_field(at_golden_np("magnetic_wave"), wiring="as_written").M),
        ("dicotron_standard", init_diocotron_field(at_golden_np("dicotron"), orientation="standard").M),
        ("dicotron_matlab_bug", init_diocotron_field(at_golden_np("dicotron"), orientation="matlab_bug").M),
        ("constant", init_constant_field(at_golden_np("constant")).M),
    ]
    for tag, M in fields:
        gold = _golden_field(tag)
        assert M.shape == gold.shape == (15, GOLDEN_NP, GOLDEN_NP), "%s shape" % tag
        np.testing.assert_allclose(M, gold, rtol=0, atol=1e-11, err_msg="%s IC field" % tag)
    return "init OK (7 fields at Np=%d: waves+as_written, diocotron std+bug, constant)" % GOLDEN_NP


def check_dt():
    rows = _load("dt.csv")
    for ci, vmax, t, dt_gold in rows:
        case = get_case(DT_CASES[int(ci) - 1])
        dt = compute_dt(float(vmax), case, float(t))
        # Relative tolerance: robust to harmless FP reassociation, still catches a
        # policy error (the dt values span 1e-6..1e-3).
        assert abs(dt - dt_gold) <= 1e-15 + 1e-12 * abs(dt_gold), "dt mismatch %s vmax=%g t=%g: %g vs %g" % (
            case.name, vmax, t, dt, dt_gold)
    return "dt OK (%d probes vs compute_dt.m: CFL bound, source caps, elseif, final clamp)" % len(rows)


CHECKS = [check_linearized, check_init, check_dt]


def main() -> int:
    if not G.exists():
        print("CHECK-GOLDENS: goldens/ missing; regenerate with the golden_*_gen.m scripts", file=sys.stderr)
        return 1
    failures = []
    for fn in CHECKS:
        try:
            print("  OK   %-16s %s" % (fn.__name__, fn()))
        except Exception as exc:  # noqa: BLE001
            failures.append(fn.__name__)
            print("  FAIL %-16s %s" % (fn.__name__, exc))
    if failures:
        print("CHECK-GOLDENS: %d/%d FAILED" % (len(failures), len(CHECKS)), file=sys.stderr)
        return 1
    print("CHECK-GOLDENS: OK (%d checks vs Octave goldens)" % len(CHECKS))
    return 0


if __name__ == "__main__":
    sys.exit(main())
